### ISSUE TITLE
DEV: Create footer

### ISSUE THREAD

**Issue by deenhaque** [cublueprint/cublueprint-react-website#3]
The project currently has a not-yet-implemented Footer component.

Please create the Footer so it looks like the one in our [Figma](https://www.figma.com/file/Qt7bGynNItu0hUvPu0EPGa/Draft-Website-Design?node-id=2%3A21) pages and it contains functional links.

Considering that the pages themselves are not yet implemented, simply having the page links for now will suffice,

**Comment by Seneli** [comment]
Not sure how to add in styled components to this so if anyone has any suggestions that would be amazing :)
